//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport.BLL.TdmWsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tdmWsService.webservice.cape.avicit/", ConfigurationName="TdmWsService.TdmWsService")]
    public interface TdmWsService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmWsService.getPyParseInfoResponse getPyParseInfo(DataImport.BLL.TdmWsService.getPyParseInfo request);
        
        // CODEGEN: 命名空间  的元素名称 taskId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmWsService.getTechDocumentInfoResponse getTechDocumentInfo(DataImport.BLL.TdmWsService.getTechDocumentInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPyParseInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPyParseInfo", Namespace="http://tdmWsService.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmWsService.getPyParseInfoBody Body;
        
        public getPyParseInfo() {
        }
        
        public getPyParseInfo(DataImport.BLL.TdmWsService.getPyParseInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPyParseInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getPyParseInfoBody() {
        }
        
        public getPyParseInfoBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPyParseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPyParseInfoResponse", Namespace="http://tdmWsService.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmWsService.getPyParseInfoResponseBody Body;
        
        public getPyParseInfoResponse() {
        }
        
        public getPyParseInfoResponse(DataImport.BLL.TdmWsService.getPyParseInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPyParseInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getPyParseInfoResponseBody() {
        }
        
        public getPyParseInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechDocumentInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechDocumentInfo", Namespace="http://tdmWsService.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmWsService.getTechDocumentInfoBody Body;
        
        public getTechDocumentInfo() {
        }
        
        public getTechDocumentInfo(DataImport.BLL.TdmWsService.getTechDocumentInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTechDocumentInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskId;
        
        public getTechDocumentInfoBody() {
        }
        
        public getTechDocumentInfoBody(string taskId) {
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechDocumentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechDocumentInfoResponse", Namespace="http://tdmWsService.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmWsService.getTechDocumentInfoResponseBody Body;
        
        public getTechDocumentInfoResponse() {
        }
        
        public getTechDocumentInfoResponse(DataImport.BLL.TdmWsService.getTechDocumentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTechDocumentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTechDocumentInfoResponseBody() {
        }
        
        public getTechDocumentInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TdmWsServiceChannel : DataImport.BLL.TdmWsService.TdmWsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TdmWsServiceClient : System.ServiceModel.ClientBase<DataImport.BLL.TdmWsService.TdmWsService>, DataImport.BLL.TdmWsService.TdmWsService {
        
        public TdmWsServiceClient() {
        }
        
        public TdmWsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TdmWsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmWsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmWsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmWsService.getPyParseInfoResponse DataImport.BLL.TdmWsService.TdmWsService.getPyParseInfo(DataImport.BLL.TdmWsService.getPyParseInfo request) {
            return base.Channel.getPyParseInfo(request);
        }
        
        public string getPyParseInfo(string arg0, string arg1) {
            DataImport.BLL.TdmWsService.getPyParseInfo inValue = new DataImport.BLL.TdmWsService.getPyParseInfo();
            inValue.Body = new DataImport.BLL.TdmWsService.getPyParseInfoBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            DataImport.BLL.TdmWsService.getPyParseInfoResponse retVal = ((DataImport.BLL.TdmWsService.TdmWsService)(this)).getPyParseInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmWsService.getTechDocumentInfoResponse DataImport.BLL.TdmWsService.TdmWsService.getTechDocumentInfo(DataImport.BLL.TdmWsService.getTechDocumentInfo request) {
            return base.Channel.getTechDocumentInfo(request);
        }
        
        public string getTechDocumentInfo(string taskId) {
            DataImport.BLL.TdmWsService.getTechDocumentInfo inValue = new DataImport.BLL.TdmWsService.getTechDocumentInfo();
            inValue.Body = new DataImport.BLL.TdmWsService.getTechDocumentInfoBody();
            inValue.Body.taskId = taskId;
            DataImport.BLL.TdmWsService.getTechDocumentInfoResponse retVal = ((DataImport.BLL.TdmWsService.TdmWsService)(this)).getTechDocumentInfo(inValue);
            return retVal.Body.@return;
        }
    }
}
