//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport.BLL.TdmToMpmWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", ConfigurationName="TdmToMpmWebservice.TdmToMpmWebservice")]
    public interface TdmToMpmWebservice {
        
        // CODEGEN: 命名空间  的元素名称 taskTimeInfoXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoResponse updateTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfo request);
        
        // CODEGEN: 命名空间  的元素名称 msg 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToMpmWebservice.getMsgResponse getMsg(DataImport.BLL.TdmToMpmWebservice.getMsg request);
        
        // CODEGEN: 命名空间  的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoResponse listTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfo request);
        
        // CODEGEN: 命名空间  的元素名称 taskInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskResponse receiveMpmTask(DataImport.BLL.TdmToMpmWebservice.receiveMpmTask request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTdmTaskTimesInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTdmTaskTimesInfo", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoBody Body;
        
        public updateTdmTaskTimesInfo() {
        }
        
        public updateTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateTdmTaskTimesInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskTimeInfoXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string method;
        
        public updateTdmTaskTimesInfoBody() {
        }
        
        public updateTdmTaskTimesInfoBody(string taskTimeInfoXml, string method) {
            this.taskTimeInfoXml = taskTimeInfoXml;
            this.method = method;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTdmTaskTimesInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTdmTaskTimesInfoResponse", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoResponseBody Body;
        
        public updateTdmTaskTimesInfoResponse() {
        }
        
        public updateTdmTaskTimesInfoResponse(DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateTdmTaskTimesInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public updateTdmTaskTimesInfoResponseBody() {
        }
        
        public updateTdmTaskTimesInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMsg", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.getMsgBody Body;
        
        public getMsg() {
        }
        
        public getMsg(DataImport.BLL.TdmToMpmWebservice.getMsgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMsgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        public getMsgBody() {
        }
        
        public getMsgBody(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMsgResponse", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.getMsgResponseBody Body;
        
        public getMsgResponse() {
        }
        
        public getMsgResponse(DataImport.BLL.TdmToMpmWebservice.getMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getMsgResponseBody() {
        }
        
        public getMsgResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmTaskTimesInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmTaskTimesInfo", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoBody Body;
        
        public listTdmTaskTimesInfo() {
        }
        
        public listTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmTaskTimesInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public listTdmTaskTimesInfoBody() {
        }
        
        public listTdmTaskTimesInfoBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmTaskTimesInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmTaskTimesInfoResponse", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoResponseBody Body;
        
        public listTdmTaskTimesInfoResponse() {
        }
        
        public listTdmTaskTimesInfoResponse(DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmTaskTimesInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listTdmTaskTimesInfoResponseBody() {
        }
        
        public listTdmTaskTimesInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMpmTask {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMpmTask", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskBody Body;
        
        public receiveMpmTask() {
        }
        
        public receiveMpmTask(DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class receiveMpmTaskBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskInfo;
        
        public receiveMpmTaskBody() {
        }
        
        public receiveMpmTaskBody(string taskInfo) {
            this.taskInfo = taskInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMpmTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMpmTaskResponse", Namespace="http://tdmToMpmWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskResponseBody Body;
        
        public receiveMpmTaskResponse() {
        }
        
        public receiveMpmTaskResponse(DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class receiveMpmTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public receiveMpmTaskResponseBody() {
        }
        
        public receiveMpmTaskResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TdmToMpmWebserviceChannel : DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TdmToMpmWebserviceClient : System.ServiceModel.ClientBase<DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice>, DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice {
        
        public TdmToMpmWebserviceClient() {
        }
        
        public TdmToMpmWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TdmToMpmWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmToMpmWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmToMpmWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoResponse DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice.updateTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfo request) {
            return base.Channel.updateTdmTaskTimesInfo(request);
        }
        
        public string updateTdmTaskTimesInfo(string taskTimeInfoXml, string method) {
            DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfo inValue = new DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfo();
            inValue.Body = new DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoBody();
            inValue.Body.taskTimeInfoXml = taskTimeInfoXml;
            inValue.Body.method = method;
            DataImport.BLL.TdmToMpmWebservice.updateTdmTaskTimesInfoResponse retVal = ((DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice)(this)).updateTdmTaskTimesInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToMpmWebservice.getMsgResponse DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice.getMsg(DataImport.BLL.TdmToMpmWebservice.getMsg request) {
            return base.Channel.getMsg(request);
        }
        
        public string getMsg(string msg) {
            DataImport.BLL.TdmToMpmWebservice.getMsg inValue = new DataImport.BLL.TdmToMpmWebservice.getMsg();
            inValue.Body = new DataImport.BLL.TdmToMpmWebservice.getMsgBody();
            inValue.Body.msg = msg;
            DataImport.BLL.TdmToMpmWebservice.getMsgResponse retVal = ((DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice)(this)).getMsg(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoResponse DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice.listTdmTaskTimesInfo(DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfo request) {
            return base.Channel.listTdmTaskTimesInfo(request);
        }
        
        public string listTdmTaskTimesInfo(string loginName) {
            DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfo inValue = new DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfo();
            inValue.Body = new DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoBody();
            inValue.Body.loginName = loginName;
            DataImport.BLL.TdmToMpmWebservice.listTdmTaskTimesInfoResponse retVal = ((DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice)(this)).listTdmTaskTimesInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskResponse DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice.receiveMpmTask(DataImport.BLL.TdmToMpmWebservice.receiveMpmTask request) {
            return base.Channel.receiveMpmTask(request);
        }
        
        public string receiveMpmTask(string taskInfo) {
            DataImport.BLL.TdmToMpmWebservice.receiveMpmTask inValue = new DataImport.BLL.TdmToMpmWebservice.receiveMpmTask();
            inValue.Body = new DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskBody();
            inValue.Body.taskInfo = taskInfo;
            DataImport.BLL.TdmToMpmWebservice.receiveMpmTaskResponse retVal = ((DataImport.BLL.TdmToMpmWebservice.TdmToMpmWebservice)(this)).receiveMpmTask(inValue);
            return retVal.Body.@return;
        }
    }
}
