//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport.BLL.TdmToZkWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", ConfigurationName="TdmToZkWebservice.TdmToZkWebservice")]
    public interface TdmToZkWebservice {
        
        // CODEGEN: 命名空间  的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmResponse addAtachFileInfo2Tdm(DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2Tdm request);
        
        // CODEGEN: 命名空间  的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.validateUserInfoResponse validateUserInfo(DataImport.BLL.TdmToZkWebservice.validateUserInfo request);
        
        // CODEGEN: 命名空间  的元素名称 resourceArea 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.equipmentStateResponse equipmentState(DataImport.BLL.TdmToZkWebservice.equipmentState request);
        
        // CODEGEN: 命名空间  的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoResponse listTdmProjectInfo(DataImport.BLL.TdmToZkWebservice.listTdmProjectInfo request);
        
        // CODEGEN: 命名空间  的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.modifyActualDateResponse modifyActualDate(DataImport.BLL.TdmToZkWebservice.modifyActualDate request);
        
        // CODEGEN: 命名空间  的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateResponse modifyTdmDeliveryListState(DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListState request);
        
        // CODEGEN: 命名空间  的元素名称 taskIds 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateResponse updateTdmTaskState(DataImport.BLL.TdmToZkWebservice.updateTdmTaskState request);
        
        // CODEGEN: 命名空间  的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.taskReportByClientResponse taskReportByClient(DataImport.BLL.TdmToZkWebservice.taskReportByClient request);
        
        // CODEGEN: 命名空间  的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.verificationReportStateResponse verificationReportState(DataImport.BLL.TdmToZkWebservice.verificationReportState request);
        
        // CODEGEN: 命名空间  的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataImport.BLL.TdmToZkWebservice.listTdmTasksResponse listTdmTasks(DataImport.BLL.TdmToZkWebservice.listTdmTasks request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAtachFileInfo2Tdm {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAtachFileInfo2Tdm", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmBody Body;
        
        public addAtachFileInfo2Tdm() {
        }
        
        public addAtachFileInfo2Tdm(DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addAtachFileInfo2TdmBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string size;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string path;
        
        public addAtachFileInfo2TdmBody() {
        }
        
        public addAtachFileInfo2TdmBody(string id, string attName, string size, string path) {
            this.id = id;
            this.attName = attName;
            this.size = size;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAtachFileInfo2TdmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAtachFileInfo2TdmResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmResponseBody Body;
        
        public addAtachFileInfo2TdmResponse() {
        }
        
        public addAtachFileInfo2TdmResponse(DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addAtachFileInfo2TdmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addAtachFileInfo2TdmResponseBody() {
        }
        
        public addAtachFileInfo2TdmResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserInfo", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.validateUserInfoBody Body;
        
        public validateUserInfo() {
        }
        
        public validateUserInfo(DataImport.BLL.TdmToZkWebservice.validateUserInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateUserInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserInfoBody() {
        }
        
        public validateUserInfoBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserInfoResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.validateUserInfoResponseBody Body;
        
        public validateUserInfoResponse() {
        }
        
        public validateUserInfoResponse(DataImport.BLL.TdmToZkWebservice.validateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validateUserInfoResponseBody() {
        }
        
        public validateUserInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class equipmentState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="equipmentState", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.equipmentStateBody Body;
        
        public equipmentState() {
        }
        
        public equipmentState(DataImport.BLL.TdmToZkWebservice.equipmentStateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class equipmentStateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resourceArea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resourceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceName;
        
        public equipmentStateBody() {
        }
        
        public equipmentStateBody(string resourceArea, string resourceCode, string resourceName) {
            this.resourceArea = resourceArea;
            this.resourceCode = resourceCode;
            this.resourceName = resourceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class equipmentStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="equipmentStateResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.equipmentStateResponseBody Body;
        
        public equipmentStateResponse() {
        }
        
        public equipmentStateResponse(DataImport.BLL.TdmToZkWebservice.equipmentStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class equipmentStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public equipmentStateResponseBody() {
        }
        
        public equipmentStateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmProjectInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmProjectInfo", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoBody Body;
        
        public listTdmProjectInfo() {
        }
        
        public listTdmProjectInfo(DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmProjectInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public listTdmProjectInfoBody() {
        }
        
        public listTdmProjectInfoBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmProjectInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmProjectInfoResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoResponseBody Body;
        
        public listTdmProjectInfoResponse() {
        }
        
        public listTdmProjectInfoResponse(DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmProjectInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listTdmProjectInfoResponseBody() {
        }
        
        public listTdmProjectInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyActualDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyActualDate", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.modifyActualDateBody Body;
        
        public modifyActualDate() {
        }
        
        public modifyActualDate(DataImport.BLL.TdmToZkWebservice.modifyActualDateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class modifyActualDateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actualSDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string actualEDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string actualWorkHours;
        
        public modifyActualDateBody() {
        }
        
        public modifyActualDateBody(string id, string actualSDate, string actualEDate, string actualWorkHours) {
            this.id = id;
            this.actualSDate = actualSDate;
            this.actualEDate = actualEDate;
            this.actualWorkHours = actualWorkHours;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyActualDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyActualDateResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.modifyActualDateResponseBody Body;
        
        public modifyActualDateResponse() {
        }
        
        public modifyActualDateResponse(DataImport.BLL.TdmToZkWebservice.modifyActualDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class modifyActualDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public modifyActualDateResponseBody() {
        }
        
        public modifyActualDateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyTdmDeliveryListState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyTdmDeliveryListState", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateBody Body;
        
        public modifyTdmDeliveryListState() {
        }
        
        public modifyTdmDeliveryListState(DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class modifyTdmDeliveryListStateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state;
        
        public modifyTdmDeliveryListStateBody() {
        }
        
        public modifyTdmDeliveryListStateBody(string id, string state) {
            this.id = id;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyTdmDeliveryListStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyTdmDeliveryListStateResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateResponseBody Body;
        
        public modifyTdmDeliveryListStateResponse() {
        }
        
        public modifyTdmDeliveryListStateResponse(DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class modifyTdmDeliveryListStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public modifyTdmDeliveryListStateResponseBody() {
        }
        
        public modifyTdmDeliveryListStateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTdmTaskState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTdmTaskState", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateBody Body;
        
        public updateTdmTaskState() {
        }
        
        public updateTdmTaskState(DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateTdmTaskStateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginName;
        
        public updateTdmTaskStateBody() {
        }
        
        public updateTdmTaskStateBody(string taskIds, string state, string loginName) {
            this.taskIds = taskIds;
            this.state = state;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTdmTaskStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTdmTaskStateResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateResponseBody Body;
        
        public updateTdmTaskStateResponse() {
        }
        
        public updateTdmTaskStateResponse(DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateTdmTaskStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public updateTdmTaskStateResponseBody() {
        }
        
        public updateTdmTaskStateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class taskReportByClient {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="taskReportByClient", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.taskReportByClientBody Body;
        
        public taskReportByClient() {
        }
        
        public taskReportByClient(DataImport.BLL.TdmToZkWebservice.taskReportByClientBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class taskReportByClientBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public taskReportByClientBody() {
        }
        
        public taskReportByClientBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class taskReportByClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="taskReportByClientResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.taskReportByClientResponseBody Body;
        
        public taskReportByClientResponse() {
        }
        
        public taskReportByClientResponse(DataImport.BLL.TdmToZkWebservice.taskReportByClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class taskReportByClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public taskReportByClientResponseBody() {
        }
        
        public taskReportByClientResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificationReportState {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificationReportState", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.verificationReportStateBody Body;
        
        public verificationReportState() {
        }
        
        public verificationReportState(DataImport.BLL.TdmToZkWebservice.verificationReportStateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verificationReportStateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public verificationReportStateBody() {
        }
        
        public verificationReportStateBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificationReportStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificationReportStateResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.verificationReportStateResponseBody Body;
        
        public verificationReportStateResponse() {
        }
        
        public verificationReportStateResponse(DataImport.BLL.TdmToZkWebservice.verificationReportStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verificationReportStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public verificationReportStateResponseBody() {
        }
        
        public verificationReportStateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmTasks {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmTasks", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.listTdmTasksBody Body;
        
        public listTdmTasks() {
        }
        
        public listTdmTasks(DataImport.BLL.TdmToZkWebservice.listTdmTasksBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmTasksBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public listTdmTasksBody() {
        }
        
        public listTdmTasksBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listTdmTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listTdmTasksResponse", Namespace="http://tdmToZkWebservice.webservice.cape.avicit/", Order=0)]
        public DataImport.BLL.TdmToZkWebservice.listTdmTasksResponseBody Body;
        
        public listTdmTasksResponse() {
        }
        
        public listTdmTasksResponse(DataImport.BLL.TdmToZkWebservice.listTdmTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listTdmTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listTdmTasksResponseBody() {
        }
        
        public listTdmTasksResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TdmToZkWebserviceChannel : DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TdmToZkWebserviceClient : System.ServiceModel.ClientBase<DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice>, DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice {
        
        public TdmToZkWebserviceClient() {
        }
        
        public TdmToZkWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TdmToZkWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmToZkWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdmToZkWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.addAtachFileInfo2Tdm(DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2Tdm request) {
            return base.Channel.addAtachFileInfo2Tdm(request);
        }
        
        public string addAtachFileInfo2Tdm(string id, string attName, string size, string path) {
            DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2Tdm inValue = new DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2Tdm();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmBody();
            inValue.Body.id = id;
            inValue.Body.attName = attName;
            inValue.Body.size = size;
            inValue.Body.path = path;
            DataImport.BLL.TdmToZkWebservice.addAtachFileInfo2TdmResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).addAtachFileInfo2Tdm(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.validateUserInfoResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.validateUserInfo(DataImport.BLL.TdmToZkWebservice.validateUserInfo request) {
            return base.Channel.validateUserInfo(request);
        }
        
        public string validateUserInfo(string loginName, string password) {
            DataImport.BLL.TdmToZkWebservice.validateUserInfo inValue = new DataImport.BLL.TdmToZkWebservice.validateUserInfo();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.validateUserInfoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            DataImport.BLL.TdmToZkWebservice.validateUserInfoResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).validateUserInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.equipmentStateResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.equipmentState(DataImport.BLL.TdmToZkWebservice.equipmentState request) {
            return base.Channel.equipmentState(request);
        }
        
        public string equipmentState(string resourceArea, string resourceCode, string resourceName) {
            DataImport.BLL.TdmToZkWebservice.equipmentState inValue = new DataImport.BLL.TdmToZkWebservice.equipmentState();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.equipmentStateBody();
            inValue.Body.resourceArea = resourceArea;
            inValue.Body.resourceCode = resourceCode;
            inValue.Body.resourceName = resourceName;
            DataImport.BLL.TdmToZkWebservice.equipmentStateResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).equipmentState(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.listTdmProjectInfo(DataImport.BLL.TdmToZkWebservice.listTdmProjectInfo request) {
            return base.Channel.listTdmProjectInfo(request);
        }
        
        public string listTdmProjectInfo(string loginName) {
            DataImport.BLL.TdmToZkWebservice.listTdmProjectInfo inValue = new DataImport.BLL.TdmToZkWebservice.listTdmProjectInfo();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoBody();
            inValue.Body.loginName = loginName;
            DataImport.BLL.TdmToZkWebservice.listTdmProjectInfoResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).listTdmProjectInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.modifyActualDateResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.modifyActualDate(DataImport.BLL.TdmToZkWebservice.modifyActualDate request) {
            return base.Channel.modifyActualDate(request);
        }
        
        public string modifyActualDate(string id, string actualSDate, string actualEDate, string actualWorkHours) {
            DataImport.BLL.TdmToZkWebservice.modifyActualDate inValue = new DataImport.BLL.TdmToZkWebservice.modifyActualDate();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.modifyActualDateBody();
            inValue.Body.id = id;
            inValue.Body.actualSDate = actualSDate;
            inValue.Body.actualEDate = actualEDate;
            inValue.Body.actualWorkHours = actualWorkHours;
            DataImport.BLL.TdmToZkWebservice.modifyActualDateResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).modifyActualDate(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.modifyTdmDeliveryListState(DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListState request) {
            return base.Channel.modifyTdmDeliveryListState(request);
        }
        
        public string modifyTdmDeliveryListState(string id, string state) {
            DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListState inValue = new DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListState();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateBody();
            inValue.Body.id = id;
            inValue.Body.state = state;
            DataImport.BLL.TdmToZkWebservice.modifyTdmDeliveryListStateResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).modifyTdmDeliveryListState(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.updateTdmTaskState(DataImport.BLL.TdmToZkWebservice.updateTdmTaskState request) {
            return base.Channel.updateTdmTaskState(request);
        }
        
        public string updateTdmTaskState(string taskIds, string state, string loginName) {
            DataImport.BLL.TdmToZkWebservice.updateTdmTaskState inValue = new DataImport.BLL.TdmToZkWebservice.updateTdmTaskState();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateBody();
            inValue.Body.taskIds = taskIds;
            inValue.Body.state = state;
            inValue.Body.loginName = loginName;
            DataImport.BLL.TdmToZkWebservice.updateTdmTaskStateResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).updateTdmTaskState(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.taskReportByClientResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.taskReportByClient(DataImport.BLL.TdmToZkWebservice.taskReportByClient request) {
            return base.Channel.taskReportByClient(request);
        }
        
        public string taskReportByClient(string id) {
            DataImport.BLL.TdmToZkWebservice.taskReportByClient inValue = new DataImport.BLL.TdmToZkWebservice.taskReportByClient();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.taskReportByClientBody();
            inValue.Body.id = id;
            DataImport.BLL.TdmToZkWebservice.taskReportByClientResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).taskReportByClient(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.verificationReportStateResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.verificationReportState(DataImport.BLL.TdmToZkWebservice.verificationReportState request) {
            return base.Channel.verificationReportState(request);
        }
        
        public string verificationReportState(string id) {
            DataImport.BLL.TdmToZkWebservice.verificationReportState inValue = new DataImport.BLL.TdmToZkWebservice.verificationReportState();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.verificationReportStateBody();
            inValue.Body.id = id;
            DataImport.BLL.TdmToZkWebservice.verificationReportStateResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).verificationReportState(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataImport.BLL.TdmToZkWebservice.listTdmTasksResponse DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice.listTdmTasks(DataImport.BLL.TdmToZkWebservice.listTdmTasks request) {
            return base.Channel.listTdmTasks(request);
        }
        
        public string listTdmTasks(string loginName) {
            DataImport.BLL.TdmToZkWebservice.listTdmTasks inValue = new DataImport.BLL.TdmToZkWebservice.listTdmTasks();
            inValue.Body = new DataImport.BLL.TdmToZkWebservice.listTdmTasksBody();
            inValue.Body.loginName = loginName;
            DataImport.BLL.TdmToZkWebservice.listTdmTasksResponse retVal = ((DataImport.BLL.TdmToZkWebservice.TdmToZkWebservice)(this)).listTdmTasks(inValue);
            return retVal.Body.@return;
        }
    }
}
